import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/Util/ReactQueryProvider";
import Natfication from "@/Util/Natfication";
import Nav from "@/components/NavBar/Nav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ReactQueryProvider>
          <Natfication>
            <Nav />
            {children}
          </Natfication>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
